# This rule is not used by the project porch-operator itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants permissions to create, update, and delete resources within the porch.kpt.dev.
# This role is intended for users who need to manage these resources
# but should not control RBAC or manage permissions for others.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: porch-operator
    app.kubernetes.io/managed-by: kustomize
  name: packagerevision-editor-role
rules:
- apiGroups:
  - porch.kpt.dev
  resources:
  - packagerevisions
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - porch.kpt.dev
  resources:
  - packagerevisions/status
  verbs:
  - get
